# Generated by Django 3.1.3 on 2021-07-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='DoneState',
            field=models.CharField(choices=[('UNFINISHED', 'UNFINISHED'), ('FINISHED', 'FINISHED')], default='UNFINISHED', max_length=20, verbose_name='Done State'),
        ),
    ]
