# Generated by Django 3.1.3 on 2021-07-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodule', '0002_auto_20210629_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='idcode',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='ID Code'),
        ),
    ]
