# Generated by Django 3.1.3 on 2021-07-07 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testmodule', '0003_auto_20210707_0407'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChoiceQues_StudentAnswer_Admin',
        ),
        migrations.DeleteModel(
            name='ChoiceQuestions_Admin',
        ),
        migrations.DeleteModel(
            name='Choices_Admin',
        ),
        migrations.DeleteModel(
            name='Course_Admin',
        ),
        migrations.DeleteModel(
            name='CourseTaken_Admin',
        ),
        migrations.DeleteModel(
            name='FillQues_StudentAnswer_Admin',
        ),
        migrations.DeleteModel(
            name='FillQuestions_Admin',
        ),
        migrations.DeleteModel(
            name='Grades_Admin',
        ),
        migrations.DeleteModel(
            name='Student_Admin',
        ),
        migrations.DeleteModel(
            name='StudentAnswers_Admin',
        ),
        migrations.DeleteModel(
            name='Subject_Admin',
        ),
        migrations.DeleteModel(
            name='Teacher_Admin',
        ),
        migrations.DeleteModel(
            name='TestContent_Admin',
        ),
        migrations.DeleteModel(
            name='TestInfo_Admin',
        ),
        migrations.DeleteModel(
            name='TextQues_StudentAnswer_Admin',
        ),
        migrations.DeleteModel(
            name='TextQuestions_Admin',
        ),
        migrations.AlterField(
            model_name='choiceques_studentanswer',
            name='TestID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testmodule.testinfo', verbose_name='Test ID'),
        ),
        migrations.AlterField(
            model_name='fillques_studentanswer',
            name='TestID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testmodule.testinfo', verbose_name='Test ID'),
        ),
        migrations.AlterField(
            model_name='testcontent',
            name='TestID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testmodule.testinfo', verbose_name='Test ID'),
        ),
        migrations.AlterField(
            model_name='testinfo',
            name='TestCourse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testmodule.course', verbose_name='Test Course'),
        ),
        migrations.AlterField(
            model_name='testinfo',
            name='TestSubject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testmodule.subject', verbose_name='Subject Course'),
        ),
        migrations.AlterField(
            model_name='textques_studentanswer',
            name='TestID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testmodule.testinfo', verbose_name='Test ID'),
        ),
    ]
