# Generated by Django 3.1.3 on 2021-07-05 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testmodule', '0003_profile_idcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionContent', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Question Content')),
                ('ChoiceAnswer', models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='Correct Answer')),
                ('QuestionMark', models.IntegerField(verbose_name='Mark')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseID', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Course ID')),
                ('CousrseName', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Course Name')),
                ('CourseTimeStart', models.DateTimeField(verbose_name='Start Date')),
                ('CourseTimeEnd', models.DateTimeField(verbose_name='End Date')),
                ('CourseDescription', models.TextField(verbose_name='Course Description')),
            ],
        ),
        migrations.CreateModel(
            name='FillQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionContent', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Question Content')),
                ('QuestionAnswer', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Question Answer')),
                ('QuestionMark', models.IntegerField(verbose_name='Mark')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubjectID', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Subject ID')),
                ('SubjectName', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Subject Name')),
                ('SubjectDescription', models.TextField(verbose_name='Subject Description')),
            ],
        ),
        migrations.CreateModel(
            name='TextQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionContent', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Question Content')),
                ('QuestionAnswer', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Question Answer')),
                ('QuestionMark', models.IntegerField(verbose_name='Mark')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='idcode',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='identification',
        ),
        migrations.CreateModel(
            name='TestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestID', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Test ID')),
                ('TestDescription', models.TextField(verbose_name='Test Description')),
                ('TestTimeStart', models.DateTimeField(verbose_name='Start Time')),
                ('TestTimeEnd', models.DateTimeField(verbose_name='End Time')),
                ('TestChoiceQues', models.ManyToManyField(to='testmodule.ChoiceQuestions')),
                ('TestCourse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testmodule.course', verbose_name='Test Course')),
                ('TestFillQues', models.ManyToManyField(to='testmodule.FillQuestions')),
                ('TestSubject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testmodule.subject', verbose_name='Subject Course')),
                ('TestTextQues', models.ManyToManyField(to='testmodule.TextQuestions')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(blank=True, choices=[('STU', 'Student'), ('STA', 'Staff'), ('TEA', 'Teacher')], default=None, max_length=20, null=True, verbose_name='Identification')),
                ('idcode', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='ID Code')),
                ('TeacherBaseInfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(blank=True, choices=[('STU', 'Student'), ('STA', 'Staff'), ('TEA', 'Teacher')], default=None, max_length=20, null=True, verbose_name='Identification')),
                ('idcode', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='ID Code')),
                ('StudentBaseInfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestID', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Test ID')),
                ('Grade', models.FloatField(verbose_name='Grade')),
                ('StudentID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testmodule.student', verbose_name='Student')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Crouse', models.ManyToManyField(to='testmodule.Course')),
                ('Student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testmodule.student', verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='CourseSubject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testmodule.subject', verbose_name='Course Subject'),
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChoiceIndex', models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='Choice Index')),
                ('ChoiceContent', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Choice Content')),
                ('ChoiceQues', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testmodule.choicequestions', verbose_name='Choice Question')),
            ],
        ),
    ]
