# Generated by Django 3.1.3 on 2021-07-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodule', '0005_auto_20210707_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='DoneState',
            field=models.CharField(choices=[('FINISHED', 'FINISHED'), ('UNFINISHED', 'UNFINISHED')], default='UNFINISHED', max_length=20, verbose_name='Done State'),
        ),
    ]
