# Generated by Django 3.1.3 on 2021-07-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodule', '0006_auto_20210707_0546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Course'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subject'},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='CousrseName',
            new_name='CourseeName',
        ),
        migrations.AlterField(
            model_name='grades',
            name='DoneState',
            field=models.CharField(choices=[('UNFINISHED', 'UNFINISHED'), ('FINISHED', 'FINISHED')], default='UNFINISHED', max_length=20, verbose_name='Done State'),
        ),
    ]
