# Generated by Django 3.1.3 on 2021-07-07 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testmodule', '0007_auto_20210707_0550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'User Name', 'verbose_name_plural': 'User Name'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Teacher'},
        ),
    ]
