# Generated by Django 3.1.3 on 2021-07-07 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testmodule', '0008_auto_20210707_0556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choicequestions',
            options={'verbose_name': 'Question Content', 'verbose_name_plural': 'Question Content'},
        ),
        migrations.AlterModelOptions(
            name='coursetaken',
            options={'verbose_name': 'Course Taken', 'verbose_name_plural': 'Course Taken'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Student'},
        ),
    ]
