# Generated by Django 3.1.3 on 2021-07-07 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testmodule', '0009_auto_20210707_0604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choiceques_studentanswer',
            options={'verbose_name': 'Student Choice Questions Answers', 'verbose_name_plural': 'Student Choice Questions Answers'},
        ),
        migrations.AlterModelOptions(
            name='choicequestions',
            options={'verbose_name': 'Choice Question Content', 'verbose_name_plural': 'Choice Question Content'},
        ),
        migrations.AlterModelOptions(
            name='choices',
            options={'verbose_name': 'Choices Content', 'verbose_name_plural': 'Choices Content'},
        ),
        migrations.AlterModelOptions(
            name='fillques_studentanswer',
            options={'verbose_name': 'Student Fill Questions Answers', 'verbose_name_plural': 'Student Fill Questions Answers'},
        ),
        migrations.AlterModelOptions(
            name='fillquestions',
            options={'verbose_name': 'Fill Question Content', 'verbose_name_plural': 'Fill Question Content'},
        ),
        migrations.AlterModelOptions(
            name='studentanswers',
            options={'verbose_name': 'Student Answers', 'verbose_name_plural': 'Student Answers'},
        ),
        migrations.AlterModelOptions(
            name='testcontent',
            options={'verbose_name': 'Test Information', 'verbose_name_plural': 'Test Information'},
        ),
        migrations.AlterModelOptions(
            name='testinfo',
            options={'verbose_name': 'TestInfo', 'verbose_name_plural': 'TestInfo'},
        ),
        migrations.AlterModelOptions(
            name='textques_studentanswer',
            options={'verbose_name': 'Student Text Questions Answers', 'verbose_name_plural': 'Student Text Questions Answers'},
        ),
        migrations.AlterModelOptions(
            name='textquestions',
            options={'verbose_name': 'Text Question Content', 'verbose_name_plural': 'Text Question Content'},
        ),
    ]
