# Generated by Django 3.1.3 on 2021-07-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodule', '0010_auto_20210707_0622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grades',
            options={'verbose_name': 'Student Grades', 'verbose_name_plural': 'Student Grades'},
        ),
        migrations.AlterField(
            model_name='grades',
            name='DoneState',
            field=models.CharField(choices=[('FINISHED', 'FINISHED'), ('UNFINISHED', 'UNFINISHED')], default='UNFINISHED', max_length=20, verbose_name='Done State'),
        ),
    ]
