# Generated by Django 3.1.3 on 2021-07-07 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testmodule', '0011_auto_20210707_0623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profile'},
        ),
    ]
