# Generated by Django 3.1.3 on 2021-07-10 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testmodule', '0012_auto_20210707_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='courseTaught',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testmodule.course', verbose_name='Course'),
        ),
    ]
