# Generated by Django 3.1.3 on 2021-07-10 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testmodule', '0013_teacher_coursetaught'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='courseTaught',
        ),
        migrations.AlterField(
            model_name='grades',
            name='DoneState',
            field=models.CharField(choices=[('UNFINISHED', 'UNFINISHED'), ('FINISHED', 'FINISHED')], default='UNFINISHED', max_length=20, verbose_name='Done State'),
        ),
        migrations.CreateModel(
            name='CourseTaught',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestTimeStart', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Start Time')),
                ('TestTimeEnd', models.DateTimeField(blank=True, default=None, null=True, verbose_name='End Time')),
                ('Crouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testmodule.course', verbose_name='Course Name')),
                ('Teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testmodule.teacher', verbose_name='Student Name')),
            ],
            options={
                'verbose_name': 'Course Taken',
                'verbose_name_plural': 'Course Taken',
            },
        ),
    ]
