# Generated by Django 3.1.3 on 2021-07-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodule', '0015_auto_20210711_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='CourseTimeEnd',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='CourseTimeStart',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='GradeDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Grade Date'),
        ),
    ]
