# Generated by Django 3.1.3 on 2021-07-11 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testmodule', '0016_auto_20210711_0517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fillquestions',
            old_name='FillExplanation',
            new_name='QuestionExplanation',
        ),
    ]
